[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
src_filter = +<main.cpp>
build_flags =
    -DROBOT_ARM_AP_NAME='"ESP32-Roboterarm"'
    -DROBOT_ARM_AP_PASSWORD='"robotarm123"'
lib_deps =
    ESP32Servo
